server:
  port: 8000

spring:
  application:
    name: medical-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-data
          uri: lb://PATIENT-DATA-COLLECTOR
          predicates:
            - Path=/api/vital-signs/**
          filters:
            - StripPrefix=1
        - id: health-analyzer
          uri: lb://HEALTH-ANALYZER
          predicates:
            - Path=/api/analysis/**
          filters:
            - StripPrefix=1
        - id: care-notifier
          uri: lb://CARE-NOTIFIER
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
 
